---
# tasks file for roles/ecspresso
- name: check installed ecspresso
  command: bash -lc "which ecspresso"
  register: ecspresso_exists
  changed_when: False
  ignore_errors: yes

- name: download ecspresso
  become: true
  get_url:
    url: https://github.com/kayac/ecspresso/releases/download/v{{espresso_version}}/ecspresso_{{espresso_version}}_linux_amd64.tar.gz
    dest: /tmp

- name: unarchive
  become: true
  unarchive:
    src: /tmp/ecspresso_{{espresso_version}}_linux_amd64.tar.gz
    dest: /tmp
    remote_src: yes
  when: ecspresso_exists is failed

- name: install ecspresso
  become: true
  command: mv /tmp/ecspresso /usr/local/bin/ecspresso
  when: ecspresso_exists is failed

- name: Change file ownership, group and permissions
  become: true
  file:
    path: /usr/local/bin/ecspresso
    owner: root
    group: root
    mode: '0755'
  when: ecspresso_exists is failed
