---
# tasks file for roles/ctags
- name: check installed ctags
  command: bash -lc "ctags --version"
  register: ctags_exists
  changed_when: False
  ignore_errors: yes

- include: ubuntu20.yml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version == "20"
    - ctags_exists is failed
