---
# tasks file for roles/git

- name: debug
  debug:
    msg: "{{ ansible_distribution }}"

- include: ubuntu20.yml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version == "20"
