---

# config
- name: check exists {{ home_path }}/.ssh/config
  stat:
    path: ~/.ssh/config
  register: check_exists_config
#
#- name: Remove {{ home_path }}/.ssh/config if exists
#  file:
#    path: "{{ home_path }}/.ssh/config"
#    state: absent
#  when: check_exists_config.stat.exists is true
#
#- name: check exists {{ home_path }}/.ssh/config
#  stat:
#    path: ~/.ssh/config
#  register: check_exists_config
#
#- name: debug
#  debug:
#    msg: "{{ check_exists_config }}"

- name: make {{ home_path }}/.ssh/config. If not exists
  file:
    path: "{{ home_path }}/.ssh/config"
    state: touch
    mode: "0600"
  when: check_exists_config.stat.exists is false

- name: Write .ssh/config
  blockinfile:
    path: "{{ home_path }}/.ssh/config"
    block: |
      Host *
          StrictHostKeyChecking no
  when: check_exists_config.stat.exists is true

#- name: Premission .ssh/*
#  file:
#    path: "{{ home_path }}/.ssh/*"
#    state: file
#    mode: '0600'
#  when: True
