---
# tasks file for roles/nvim

- name: check installed nvim
  command: bash -lc "nvim --version"
  register: nvim_exists
  changed_when: False
  ignore_errors: yes

- name: pip-nvim install when not installed
  command:  bash -lc "{{ pyenv_path }}/shims/pip install neovim"
  when: nvim_exists is failed

- include: ubuntu20.yml
  when:
    - nvim_exists is failed
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_major_version == "20"

- name: nvim install when not installed
  command: bash -lc "mkdir -p ~/.config/nvim && touch ~/.config/nvim/init.vim && echo 'source ~/.vimrc' > ~/.config/nvim/init.vim"
  when: nvim_exists is failed
